<?php $pageTitle='About Sash Tech | Creative Digital Agency';$pageDescription='Meet Sash Tech, a multidisciplinary creative agency combining design, technology and growth strategy.';include 'includes/header.php'; ?>
<section class="page-hero"><div class="container"><span class="eyebrow">ABOUT SASH TECH</span><h1>Creative thinking with a technical edge.</h1><p>We help ambitious brands and creators move from scattered ideas to clear, high-quality digital execution.</p></div></section>
<section><div class="container two-col"><div class="reveal"><span class="eyebrow">WHAT WE DO BEST</span><h2>Integrated design, technical precision, and modern strategy under one roof.</h2></div><div class="reveal"><p><strong>Web Architecture & Technical SEO:</strong> Building fast, responsive, and scalable web solutions optimized for search performance and user conversion.</p><p><strong>2D & 3D Visual Modeling:</strong> Crafting high-end custom 3D models, 2D assets, and motion designs that give your brand a distinct visual edge.</p><p><strong>Generative Engine Optimization (GEO):</strong> Future-proofing your digital footprint so AI platforms like ChatGPT, Gemini, and Perplexity cite and recommend your brand.</p><p><strong>Digital Growth & Performance:</strong> Content creation, video editing, and strategic campaign management to keep your target audience engaged.</p></div></div></section>
<section class="dark-section"><div class="container"><div class="section-head"><div><span class="eyebrow">HOW WE TURN VISION INTO EXECUTION</span><h2>We eliminate friction, unnecessary handoffs, and misaligned strategy by keeping everything under one connected workflow.</h2></div></div><div class="process-steps">
  <article class="process-node reveal"><div class="step-top"><b>01</b><span class="step-line"></span></div><h3>Discovery & Strategy</h3><p>We start by understanding your exact business goals, audience expectations, and technical requirements.</p></article>
  <article class="process-node reveal"><div class="step-top"><b>02</b><span class="step-line"></span></div><h3>Creative & Visual Design</h3><p>Our team builds out modern UI/UX layouts, custom 2D/3D assets, and cohesive branding structures.</p></article>
  <article class="process-node reveal"><div class="step-top"><b>03</b><span class="step-line"></span></div><h3>Engineering & Optimization</h3><p>We write clean code, optimize site performance, and configure schema and technical SEO markers.</p></article>
  <article class="process-node reveal"><div class="step-top"><b>04</b><span class="step-line"></span></div><h3>Launch & Continuous Scale</h3><p>We deploy your project smoothly and provide ongoing support, content, and growth strategy.</p></article>
</div></div></section>
<section class="dark-section"><div class="container two-col"><div class="reveal"><span class="eyebrow">BRANDING & UI SHOWCASE</span><h2>Where clarity, aesthetics, and growth strategy come together.</h2><p>From brand identity to polished web experiences, our work is designed to feel distinctive, strategic, and easy to trust at every touchpoint.</p><ul class="feature-list"><li>Elegant brand direction with a conversion-minded layout</li><li>High-end visual systems built for modern digital audiences</li><li>Creative presentation that adds credibility and visual depth</li></ul></div><div class="reveal" style="display:grid; grid-template-columns:1fr 1fr; gap:16px;"><div style="display:flex; flex-direction:column; gap:16px;"><img src="assets/images/branding/branding1.webp" alt="Branding showcase" style="width:100%; height:220px; object-fit:cover; border-radius:18px; border:1px solid rgba(255,255,255,.12); box-shadow:0 20px 40px rgba(0,0,0,.35);"><img src="assets/images/newimages/Web Design & Technical SEO.png" alt="UI design showcase" style="width:100%; height:220px; object-fit:cover; border-radius:18px; border:1px solid rgba(255,255,255,.12); box-shadow:0 20px 40px rgba(0,0,0,.35);"></div><img src="assets/images/newimages/about us (1).png" alt="About Sash Tech creative workflow" style="width:100%; height:456px; object-fit:cover; border-radius:18px; border:1px solid rgba(255,255,255,.12); box-shadow:0 20px 40px rgba(0,0,0,.35);"></div></div></section>
<section><div class="container"><div class="section-head"><div><span class="eyebrow">START YOUR NEXT PROJECT</span><h2>Ready to build something bold and memorable?</h2><p>Let’s discuss your project requirements, target timeline, and growth goals.</p></div></div><div class="hero-actions" style=""><button class="btn btn-primary" data-popup-open>Start a Project <span>↗</span></button><a class="btn btn-outline" href="portfolio.php">View Our Work <span>→</span></a></div></div></section>
<?php include 'includes/footer.php'; ?>
