<?php $pageTitle='Service Pricing & Custom Quotes | Sash Tech';$pageDescription='Explore flexible pricing options for illustration, animation, video editing, web design, SEO, GEO and digital marketing services.';include 'includes/header.php'; ?>
<section class="page-hero pricing-hero"><div class="container"><span class="eyebrow">PRICING & SERVICES</span><h1>Choose the service you need. We’ll shape the right scope.</h1><p>Every project is quoted according to complexity, deliverables, timeline and revision requirements. Select a service below to request a tailored estimate.</p></div></section>
<section class="pricing-services"><div class="container"><div class="section-head"><div><span class="eyebrow">SERVICE OPTIONS</span><h2>Flexible pricing for every creative need.</h2></div><p>No hidden packages or one-size-fits-all pricing. You receive a clear scope, deliverables and timeline before work begins.</p></div><div class="pricing-service-grid">
<?php foreach($services as $slug=>$service): ?>
<article class="service-price-card reveal"><div class="service-price-icon"><?=e($service['icon'])?></div><span class="eyebrow"><?=e(strtoupper($service['title']))?></span><h3><?=e($service['title'])?></h3><p><?=e($service['short'])?></p><ul><?php foreach($service['items'] as $item): ?><li><?=e($item)?></li><?php endforeach; ?></ul><div class="price-card-bottom"><span class="quote-label">Custom project quote</span><button class="btn btn-primary" data-popup-open>Get a Quote <span>→</span></button></div></article>
<?php endforeach; ?>
</div></div></section>
<section class="dark-section pricing-process"><div class="container"><div class="center-head"><span class="eyebrow">HOW PRICING WORKS</span><h2>Simple, transparent and based on your scope.</h2></div><div class="process-grid"><article class="process-step"><b>01</b><h3>Choose a Service</h3><p>Tell us which service and deliverables you need.</p></article><article class="process-step"><b>02</b><h3>Share Your Brief</h3><p>Provide your goals, timeline and useful references.</p></article><article class="process-step"><b>03</b><h3>Receive a Proposal</h3><p>We send a clear quote with scope, milestones and revisions.</p></article><article class="process-step"><b>04</b><h3>Start Production</h3><p>Once approved, your project enters the production schedule.</p></article></div></div></section>
<?php include 'includes/footer.php'; ?>
