<?php
$services = [
'web-design-technical-seo' => ['title'=>'Web Design & Technical SEO','short'=>'Fast, polished websites supported by practical, measurable search optimization.','icon'=>'◈','items'=>['Website Designing','Search Engine Optimization','Responsive Development & Tuning'],'image'=>'Web Design & Technical SEO.png'], 
'video-production-editing' => ['title'=>'Video Production & Editing','short'=>'From high-converting short-form clips to narrative-driven long-form content, we produce and edit video content designed to captivate your audience and scale your online presence. ','icon'=>'▶','items'=>['Long-Form Video Editing','Short-Form Video Editing','Sound Design & Color Grading'],'image'=>'Video Production & Editing (1).png'],
'creator-growth-youtube-strategy' => ['title'=>'Creator Growth & YouTube Strategy','short'=>'Algorithm-optimized SEO, thumbnail strategies, and distribution systems designed to turn casual viewers into loyal subscribers.','icon'=>'↗','items'=>['YouTube SEO','Audience Scaling Strategies','Thumbnail Design & Optimization'],'image'=>'Creator Growth & YouTube Strategy 1 (1).png'],
'illustration-creative-artwork' => ['title'=>'Illustration & Creative Artwork','short'=>'Distinctive covers, characters and bespoke artwork created to make ideas unforgettable.','icon'=>'✦','items'=>['Book & Novel Covers','Character Designing','Custom Artworks'],'image'=>'Illustration & Creative Artwork 2 (1).png'],
 '2d-3d-modeling-animation' => ['title'=>'2D & 3D Modeling & Animation','short'=>'Professional 2D & 3D modeling, high-quality animation, and scroll-stopping custom GIF experiences for modern brands.','icon'=>'◉','items'=>['2D Modeling & Animation','3D Modeling & Animation','Custom GIFs & Motion Graphics'],'image'=>'Animation & Motion Graphics (1).png'],
 'ai-search-optimization' => ['title'=>'Why Your Business Needs GEO','short'=>'As search behavior shifts from traditional search engine results pages to generative AI answers, relying on keyword-dense SEO alone is no longer enough. Modern users ask conversational questions and expect direct, cited answers.','icon'=>'◎','items'=>['Entity & Knowledge Graph Building','Citation & Authority Engineering','Semantic & Intent-Driven Content'],'image'=>'AI Search Optimization (GEO).png'],
 'digital-marketing-paid-acquisition' => ['title'=>'Digital Marketing & Paid Acquisition','short'=>'Content, social and paid campaigns designed to turn attention into growth.','icon'=>'⚡','items'=>['Social Media Marketing','Paid Advertising (PPC)','Content Marketing & Copywriting'],'image'=>'Digital Marketing & Paid Acquisition.png'],
];
